name: flutter_config
description: Plugin that exposes environment variables to your Dart code in Flutter as well as to your native code in iOS and Android. Bring some 12 factor love to your Flutter apps
version: 2.0.0
homepage: https://github.com/ByneappLLC/flutter_config

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.byneapp.flutter_config
        pluginClass: FlutterConfigPlugin
      ios:
        pluginClass: FlutterConfigPlugin
      web:
        pluginClass: FlutterConfigPluginWeb
        fileName: flutter_config_web.dart

